sudo: false

language: python

python:
  - "2.7"
  - "2.6"
  - "pypy"

addons:
  apt_packages:
    - iverilog

install:
  - pip install -r requirements.txt

script: py.test

notifications:
  email: false
