# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "2.6"
  - "pypy"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq iverilog

install:
  - pip install -r requirements.txt

script: py.test

notifications:
  email:
    on_success: change
    on_failure: change
